#!/usr/bin/python
"""
C++ metaprogramming shell launcher

This utility starts the shell in CGI-mode.

Supported options:

 -h, --help             Display this help message
 -i, --includes <path>  The root of the header collection (default: /usr/include/headers)
 -s, --shell <path>     Path of the shell binary
 -l, --log <path>       Log into that file
 -p, --peer <name>      Name of remote peer
 -u, --url <url>        The URL with the GET parameters
                        Accepted GET parameters:
                          boost_version=<version>
                          loki_version=<version>
"""

import sys
import getopt
import urlparse
import os
import resource
import time
import fcntl
import json
import datetime

def append_to_file(filename, s):
  f = open(filename, 'a')
  fcntl.flock(f, fcntl.LOCK_EX)
  try:
    f.write(s)
  finally:
    fcntl.flock(f, fcntl.LOCK_UN)
  f.close()

def log(filename, msg):
  if filename != '':
    suffix = datetime.datetime.now().strftime("_%Y_%m_%d")
    msg['timestamp'] = time.time()
    append_to_file(filename + suffix, json.dumps(msg) + '\n')

def allowed_version_char(c):
  return c.isalnum() or c == '.'

def valid_version(s):
  return \
    all([allowed_version_char(c) for c in s]) \
    and any([c.isalnum() for c in s])

def limit_memory(mb):
  b = mb * 1024 * 1024
  resource.setrlimit(resource.RLIMIT_AS, (b, b))

def main():
  try:
    opts, args = getopt.getopt(
      sys.argv[1:],
      'hs:i:u:l:p:',
      ['help', 'shell=', 'includes=', 'url=', 'log=', 'peer=']
    )
  except getopt.error, msg:
    print msg
    print "Getting help: --help"
    sys.exit(1)
  
  binary = ''
  includes = '/usr/include/headers'
  boost_version = '1.54.0'
  loki_version = '0.1.7'
  logfile = ''
  peer = ''
  url = ''

  for o, a in opts:
    if o in ('-h', '--help'):
      print __doc__
      sys.exit(0)
    elif o in ('-l', '--log'):
      logfile = a
    elif o in ('-p', '--peer'):
      peer = a
    elif o in ('-s', '--shell'):
      binary = a
    elif o in ('-i', '--includes'):
      includes = a
    elif o in ('-u', '--url'):
      url = a
      errors = []
      for name, value in urlparse.parse_qsl(urlparse.urlparse(a).query):
        if name == 'boost_version':
          if valid_version(value):
            boost_version = value
          else:
            errors.append('Invalid Boost version: ' + value)
        elif name == 'loki_version':
          if valid_version(value):
            loki_version = value
          else:
            errors.append('Invalid Loki version: ' + value)
        else:
          errors.append('Invalid GET option: ' + name)
      if len(errors) > 0:
        print '\n'.join(errors)
        sys.exit(1)

  if binary == '':
    print 'The shell binary has not been provided.'
    print 'Getting help: --help'
    sys.exit(1)
   
  shell_args = [
    binary,
    '-I', '%s/boost/%s' % (includes, boost_version),
    '-I', '%s/loki/%s' % (includes, loki_version)
  ]

  log(logfile, {'peer' : peer, 'cmd' : shell_args, 'url' : url})

  limit_memory(256)

  try:
    os.execvp(binary, shell_args)
  except OSError as e:
    print 'Error running the shell: %s' % (e)
    sys.exit(1)

if __name__ == '__main__':
  try:
    main()
  except SystemExit:
    raise
  except:
    print 'Uncaught exception'


