#!/bin/bash
#
# Deployment script of the online Metashell and Preshell demos
# Copyright (C) 2015, Abel Sinkovics (abel@sinkovics.hu)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function git_repo_begin {
  HOST="$1"
  USER="$2"
  NAME="$3"
  BRANCH="$4"
  DIR_NAME="${USER}_${NAME}"
  if [ -e "${DIR_NAME}" ]; then
    echo "${DIR_NAME} already exists"
  else
    git clone --recursive "https://${HOST}/${USER}/${NAME}.git" "${DIR_NAME}"
  fi
  cd "${DIR_NAME}"
  git branch "${BRANCH}" "origin/${BRANCH}"
  git checkout "${BRANCH}"
  git pull origin "${BRANCH}"
  git submodule foreach git pull
}

function git_repo_end {
  cd ..
}

function follow_git_repo {
  HOST="$1"
  USER="$2"
  NAME="$3"
  BRANCH="$4"
  HEADER_PATH="$5"
  HEADER_PATH2_SRC="$6"
  HEADER_PATH2_DST="$7"
  INCLUDE="$(pwd)/include"

  git_repo_begin "${HOST}" "${USER}" "${NAME}" "${BRANCH}"
    REV=`git rev-parse "${BRANCH}"`
    INSTALLED="${INCLUDE}/headers/${NAME}/${REV}"
    if [ ! -d "${INSTALLED}" ]
    then
      mkdir -p "${INSTALLED}"
      cp -r "${HEADER_PATH}" "${INSTALLED}"
      if [ -n "${HEADER_PATH2_SRC}" ]
      then
        mkdir -p "${INSTALLED}/${HEADER_PATH2_DST}"
        cp -r "${HEADER_PATH2_SRC}" "${INSTALLED}/${HEADER_PATH2_DST}"
      fi
    fi
    if [ "$(readlink "${INCLUDE}/headers/${NAME}/${BRANCH}")" != "${REV}" ]
    then
      rm "${INCLUDE}/headers/${NAME}/${BRANCH}"
      ln -fs "${REV}" "${INCLUDE}/headers/${NAME}/${BRANCH}"
    fi
  git_repo_end
}

function write_version_desc {
  git log -1 --pretty="%h %B" | head -1 \
    | sed 's/\\/\\\\/g' \
    | sed 's/"/\\"/g' \
    | sed 's/^/"/' | sed 's/$/\\n This demo is supported by the Eotvos Lorand University, Faculty of Informatics"/' \
    > lib/core/version_desc.hpp
}

function upgrade {
  BIN="$(pwd)/bin"
  INCLUDE="$(pwd)/include"
  USR_INCLUDE="${INCLUDE}/usr/include"
  METASHELL_INCLUDE="${INCLUDE}/metashell"

  mkdir bin

  mkdir -p "${USR_INCLUDE}"
  mkdir -p "${METASHELL_INCLUDE}"
  ln -s \
    $(ls -d /usr/include/* | egrep -v '^/usr/include/(boost|mpllibs)$') \
    "${USR_INCLUDE}"

  git_repo_begin github.com sabel83 metashell master
    REV=`git rev-parse master`
    INSTALLED_METASHELL="${BIN}/metashell_${REV}"
    INSTALLED_TEMPLIGHT="${BIN}/templight_metashell_${REV}"

    if [ ! -f "${INSTALLED_METASHELL}" ] || [ ! -f "${INSTALLED_TEMPLIGHT=}" ]
    then
      write_version_desc

      rm -rf bin
      ./build.sh
    
      METASHELL_SRC="$(pwd)"
      TEMPLIGHT_SRC="${METASHELL_SRC}/3rd/templight"
      cd bin
        TEMPLIGHT_HEADERS="${TEMPLIGHT_SRC}/$(cmake .. -DTEMPLIGHT_DEBUG=1 | egrep 'TEMPLIGHT_HEADERS = ' | sed 's/^.*3rd\/templight\/build\//build\//')"
        echo "TEMPLIGHT_HEADERS = ${TEMPLIGHT_HEADERS}"
        test/unit/metashell_unit_test \
          && ln -fs "${TEMPLIGHT_HEADERS}" "${METASHELL_INCLUDE}/templight" \
          && cp app/metashell "${INSTALLED_METASHELL}" \
          && ln -fs "${INSTALLED_METASHELL}" "${BIN}/metashell" \
          && cp app/templight_metashell "${INSTALLED_TEMPLIGHT}" \
          && ln -fs "${INSTALLED_TEMPLIGHT}" "${BIN}/templight_metashell"
      cd ..
    fi
  git_repo_end
  
  git_repo_begin github.com sabel83 headers master
    rsync -r headers "${INCLUDE}"
  git_repo_end

  git_repo_begin github.com boostorg boost master
    REV=`git rev-parse master`
    INSTALLED="${INCLUDE}/headers/boost/${REV}"
    if [ ! -d "${INSTALLED}" ]
    then
      mkdir -p "${INSTALLED}"
      for l in $(ls -d libs/*/)
      do
        cp -r "${l}include/boost" "${INSTALLED}"
      done
      ln -fs "${REV}" "${INCLUDE}/headers/boost/master"
    fi
  git_repo_end

  follow_git_repo github.com sabel83 metatest master include/metatest
  follow_git_repo github.com sabel83 mpllibs master mpllibs libs/metaparse/example/getting_started mpllibs/metaparse
  follow_git_repo github.com minamiyama1994 FTMP master include/FTMP
  follow_git_repo github.com ldionne hana master include/boost
  follow_git_repo github.com pfultz2 Ripple master ripple
  follow_git_repo github.com facebook fatal master fatal
  follow_git_repo github.com facebook fatal dev fatal
  follow_git_repo github.com ericniebler meta master include/meta
}




########
# Main #
########

export LC_ALL=C

while true
do
  cd /usr/local/share/shell_demo

  upgrade > /usr/local/share/shell_demo/last_log.txt 2>&1

  sleep 3600
done

